### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [bobbimanners/EightBall#33]
Greetings, I'm a graphic designer and I like contributing to open source projects. I'm offering my services to create a logo for yours, it's totally free and we will be working together to create the perfect logo that fits your project best.

If you accept, let me know if you have any preferences (colors, style, etc) or not.

Best regards.

**Comment by bobbimanners** [comment]
Hi Michael,

That sounds awesome!  I guess the obvious logo is a pool eight ball, which
is black.  Graphic design is not my strong point, so I will leave the
details to you :)

All the best,
Bobbi

**Comment by michaelizer** [comment]
What do you think of these? 
![eightball1](https://user-images.githubusercontent.com/35619342/40881791-68de15aa-669e-11e8-9427-8e1ae07fd4a9.png)

**Comment by bobbimanners** [comment]
Looks really awesome, but I am having trouble choosing!!

**Comment by michaelizer** [comment]
I think the four of the bottom look better, you can tell me what colour do you prefer? And I'll make the eight a bit more visible to make it scalable to smaller sizes. What do you think?

**Comment by michaelizer** [comment]
Like this
![unknown2](https://user-images.githubusercontent.com/35619342/40890947-d1d413cc-674b-11e8-86fd-9abc9edbd6a1.png)
Of course, it will have rounded corners that will make it look softer and more "friendly". What do you say?

**Comment by bobbimanners** [comment]
I was pondering on this and I think I actually like one of the top designs more - second from the left on the top row.  I like the way it looks more hand drawn.  Maybe play around with the size of the ball relative to the text - I am wondering if maybe it could be a little bigger?

**Comment by michaelizer** [comment]
You mean like this? 
![unknown](https://user-images.githubusercontent.com/35619342/40895723-013f2e02-677f-11e8-993d-ff3e57f3585f.png)
Don't worry about resolution, the original files will be upload through a pull request

**Comment by bobbimanners** [comment]
Actually the bit I really like is the script-style text of the first version.  Can we have that back, just with a bigger 8-ball logo?

**Comment by michaelizer** [comment]
I made a few variations, let me know what you think :))
![unknownyg](https://user-images.githubusercontent.com/35619342/40948096-55b54b5a-6834-11e8-927d-f36d7b63a8e8.png)

**Comment by michaelizer** [comment]
Great!, I'll upload the files on a pull request then.

**Comment by bobbimanners** [comment]
Thank you.  It is very exciting to have a proper logo :)

**Comment by michaelizer** [comment]
Ok, the files are ready. In which folder do you want me to upload them?

**Comment by bobbimanners** [comment]
Put them in the top-level `pics` folder.  Thanks :)

**Comment by michaelizer** [comment]
Done!, please check it ([#40](https://github.com/bobbimanners/EightBall/pull/40))

**Comment by bobbimanners** [comment]
Thank you - it looks great!!
